### ISSUE TITLE
Getting some weird error, only in windows.

### ISSUE THREAD

**Issue by ZeroSkill1** [ihaveamac/custom-install#21]
it works fine in linux, but not in windows. i get this error when i try to run the script (occurs in both gui and command line version):
```C:\Users\USER\Personal Documents\Programs\3DS Tools\custom-install>python3 custominstall.py -m "C:\Users\UESR\Desktop\movable.sed" -b "C:\Users\Kurdo Kadir\Desktop\boot9.bin" --sd D:/ "C:\Users\USER\Downloads\0511 - Pokemon X (US)(M7).cia"
Finding path to install to...
Reading C:\Users\USER\Downloads\application.cia
Exception ignored in: <function TypeReaderBase.close at 0x000001D0CF00D430>
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyctr\type\base\typereader.py", line 85, in close
    if self._closefd:
AttributeError: 'CIAReader' object has no attribute '_closefd'
Traceback (most recent call last):
  File "custominstall.py", line 470, in <module>
    installer.start()
  File "custominstall.py", line 184, in start
    cia = CIAReader(c, seeddb=self.seeddb)
TypeError: __init__() got an unexpected keyword argument 'seeddb'
```
All required packages are installed through pip3. Am I missing something here?
This is how I run the script:
```py -3 custominstall.py -m "C:\Users\USER\Desktop\movable.sed" -b "C:\Users\USER\Desktop\boot9.bin" --sd D:/ "C:\Users\USER\Downloads\application.cia"```

**Comment by ZeroSkill1** [comment]
Nevermind, I had the wrong version of one of the required packages. Whoops
