### ISSUE TITLE
Error InvalidRomFSHeaderError

### ISSUE THREAD

**Issue by kreyssig** [ihaveamac/custom-install#9]
PS C:\Users\gagui\Desktop\3DS\custom-install-master> py -3 custom-install.py -b boot9.bin -m movable.sed --sd "f:\\" "C:\Users\gagui\Desktop\3DS\custom-install-master\poke.cia"
Finding path to install to...
Reading CIA...
Traceback (most recent call last):
  File "custom-install.py", line 92, in <module>
    cia = CIAReader(c)
  File "C:\Users\gagui\Desktop\3DS\custom-install-master\pyctr\types\cia.py", line 174, in __init__
    self.contents[record.cindex] = NCCHReader(content_fp, case_insensitive=case_insensitive,
  File "C:\Users\gagui\Desktop\3DS\custom-install-master\pyctr\types\ncch.py", line 248, in __init__
    self.load_sections()
  File "C:\Users\gagui\Desktop\3DS\custom-install-master\pyctr\types\ncch.py", line 307, in load_sections
    self.romfs = RomFSReader(romfs_fp, case_insensitive=self._case_insensitive)
  File "C:\Users\gagui\Desktop\3DS\custom-install-master\pyctr\types\romfs.py", line 128, in __init__
    raise InvalidRomFSHeaderError('Length in RomFS Lv3 header is not 0x28')
pyctr.types.romfs.InvalidRomFSHeaderError: Length in RomFS Lv3 header is not 0x28
PS C:\Users\gagui\Desktop\3DS\custom-install-master>

**Comment by ihaveamac** [comment]
Maybe an issue with decrypting the title? Can you view the RomFS with GodMode9?
